query($query: String) {
  Page {
    media(search: $query, type: ANIME, isAdult: false, format_not: SPECIAL) {
      id
      idMal
      title {
        romaji
        english
        native
      }
      coverImage {
        medium
        large
        extraLarge
      }
      bannerImage
      format
      status
      season
      synonyms
      averageScore
      popularity
      episodes
      isLocked
      siteUrl
      description
      stats {
        scoreDistribution {
          score
          amount
        }
      }
    }
  }
}
