query($query: String) {
  Page {
    media(search: $query, type: ANIME, sort: POPULARITY_DESC, isAdult: false) {
      id
      idMal
      title {
        romaji
        english
        native
      }
      coverImage {
        medium
        large
      }
      bannerImage
      format
      status
      season
      synonyms
      averageScore
      popularity
      episodes
      isLocked
      siteUrl
    }
  }
}
